name: build_runner_helper
version: 0.1.0
description: build_runner helper to save your fingers from writing the whole command
homepage: https://github.com/vaetas/build_runner_helper

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  builder: 

dev_dependencies:
  pedantic: ^1.9.2
