name: build_runner_helper
version: 0.3.0
description: build_runner helper to save your fingers from typing the whole command
homepage: https://github.com/vaetas/build_runner_helper

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  builder: 

dependencies:
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.2
